[2023-05-23T15:46:37.681+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_token.fresh scheduled__2023-05-22T00:00:00+00:00 [queued]>
[2023-05-23T15:46:37.709+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_token.fresh scheduled__2023-05-22T00:00:00+00:00 [queued]>
[2023-05-23T15:46:37.710+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T15:46:37.713+0000] {taskinstance.py:1283} INFO - Starting attempt 3 of 6
[2023-05-23T15:46:37.713+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T15:46:37.753+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): fresh> on 2023-05-22 00:00:00+00:00
[2023-05-23T15:46:37.757+0000] {standard_task_runner.py:55} INFO - Started process 275 to run task
[2023-05-23T15:46:37.763+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'refresh_token', 'fresh', 'scheduled__2023-05-22T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/refresh_token_DAG.py', '--cfg-path', '/tmp/tmpf0z0q290']
[2023-05-23T15:46:37.764+0000] {standard_task_runner.py:83} INFO - Job 29: Subtask fresh
[2023-05-23T15:46:37.842+0000] {task_command.py:388} INFO - Running <TaskInstance: refresh_token.fresh scheduled__2023-05-22T00:00:00+00:00 [running]> on host 2a789c3fa429
[2023-05-23T15:46:37.960+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=fox
AIRFLOW_CTX_DAG_ID=refresh_token
AIRFLOW_CTX_TASK_ID=fresh
AIRFLOW_CTX_EXECUTION_DATE=2023-05-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-22T00:00:00+00:00
[2023-05-23T15:46:37.961+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: refresh() missing 1 required positional argument: 'self'
[2023-05-23T15:46:37.970+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=refresh_token, task_id=fresh, execution_date=20230522T000000, start_date=20230523T154637, end_date=20230523T154637
[2023-05-23T15:46:37.984+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 29 for task fresh (refresh() missing 1 required positional argument: 'self'; 275)
[2023-05-23T15:46:38.013+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-23T15:46:38.036+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
