[2023-05-23T15:42:34.935+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_token.fresh scheduled__2023-05-22T00:00:00+00:00 [queued]>
[2023-05-23T15:42:35.066+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_token.fresh scheduled__2023-05-22T00:00:00+00:00 [queued]>
[2023-05-23T15:42:35.066+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T15:42:35.067+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-05-23T15:42:35.067+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T15:42:35.159+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): fresh> on 2023-05-22 00:00:00+00:00
[2023-05-23T15:42:35.165+0000] {standard_task_runner.py:55} INFO - Started process 172 to run task
[2023-05-23T15:42:35.191+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'refresh_token', 'fresh', 'scheduled__2023-05-22T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/refresh_token_DAG.py', '--cfg-path', '/tmp/tmp7o0u9jpj']
[2023-05-23T15:42:35.214+0000] {standard_task_runner.py:83} INFO - Job 25: Subtask fresh
[2023-05-23T15:42:35.380+0000] {task_command.py:388} INFO - Running <TaskInstance: refresh_token.fresh scheduled__2023-05-22T00:00:00+00:00 [running]> on host 2a789c3fa429
[2023-05-23T15:42:35.662+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=fox
AIRFLOW_CTX_DAG_ID=refresh_token
AIRFLOW_CTX_TASK_ID=fresh
AIRFLOW_CTX_EXECUTION_DATE=2023-05-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-22T00:00:00+00:00
[2023-05-23T15:42:35.663+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: refresh() missing 1 required positional argument: 'self'
[2023-05-23T15:42:35.682+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=refresh_token, task_id=fresh, execution_date=20230522T000000, start_date=20230523T154234, end_date=20230523T154235
[2023-05-23T15:42:35.725+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 25 for task fresh (refresh() missing 1 required positional argument: 'self'; 172)
[2023-05-23T15:42:35.743+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-23T15:42:35.769+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
