[2023-05-25T16:57:00.102+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.transform_data manual__2023-05-24T17:09:20.161548+00:00 [queued]>
[2023-05-25T16:57:00.130+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.transform_data manual__2023-05-24T17:09:20.161548+00:00 [queued]>
[2023-05-25T16:57:00.130+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-25T16:57:00.130+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 6
[2023-05-25T16:57:00.131+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-25T16:57:00.164+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): transform_data> on 2023-05-24 17:09:20.161548+00:00
[2023-05-25T16:57:00.175+0000] {standard_task_runner.py:55} INFO - Started process 2832 to run task
[2023-05-25T16:57:00.185+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ETL', 'transform_data', 'manual__2023-05-24T17:09:20.161548+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/refresh_token_DAG.py', '--cfg-path', '/tmp/tmp2l7h29v1']
[2023-05-25T16:57:00.190+0000] {standard_task_runner.py:83} INFO - Job 216: Subtask transform_data
[2023-05-25T16:57:00.539+0000] {task_command.py:388} INFO - Running <TaskInstance: ETL.transform_data manual__2023-05-24T17:09:20.161548+00:00 [running]> on host 2fa3ade57007
[2023-05-25T16:57:00.730+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=fox
AIRFLOW_CTX_DAG_ID=ETL
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2023-05-24T17:09:20.161548+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-24T17:09:20.161548+00:00
[2023-05-25T16:57:00.732+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/refresh_token_DAG.py", line 16, in spotify
    spotify_df = spotify_df.append(ti.xcom_pull(task_ids='load_date'))
AttributeError: 'dict' object has no attribute 'append'
[2023-05-25T16:57:00.768+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL, task_id=transform_data, execution_date=20230524T170920, start_date=20230525T165700, end_date=20230525T165700
[2023-05-25T16:57:00.814+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 216 for task transform_data ('dict' object has no attribute 'append'; 2832)
[2023-05-25T16:57:00.881+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-25T16:57:01.120+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
