[2023-05-23T15:46:37.691+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_token.fresh manual__2023-05-22T16:25:59.474935+00:00 [queued]>
[2023-05-23T15:46:37.706+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_token.fresh manual__2023-05-22T16:25:59.474935+00:00 [queued]>
[2023-05-23T15:46:37.707+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T15:46:37.707+0000] {taskinstance.py:1283} INFO - Starting attempt 15 of 16
[2023-05-23T15:46:37.707+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T15:46:37.729+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): fresh> on 2023-05-22 16:25:59.474935+00:00
[2023-05-23T15:46:37.734+0000] {standard_task_runner.py:55} INFO - Started process 274 to run task
[2023-05-23T15:46:37.739+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'refresh_token', 'fresh', 'manual__2023-05-22T16:25:59.474935+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/refresh_token_DAG.py', '--cfg-path', '/tmp/tmpi774y4i3']
[2023-05-23T15:46:37.741+0000] {standard_task_runner.py:83} INFO - Job 30: Subtask fresh
[2023-05-23T15:46:37.820+0000] {task_command.py:388} INFO - Running <TaskInstance: refresh_token.fresh manual__2023-05-22T16:25:59.474935+00:00 [running]> on host 2a789c3fa429
[2023-05-23T15:46:37.928+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=fox
AIRFLOW_CTX_DAG_ID=refresh_token
AIRFLOW_CTX_TASK_ID=fresh
AIRFLOW_CTX_EXECUTION_DATE=2023-05-22T16:25:59.474935+00:00
AIRFLOW_CTX_TRY_NUMBER=15
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-22T16:25:59.474935+00:00
[2023-05-23T15:46:37.929+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: refresh() missing 1 required positional argument: 'self'
[2023-05-23T15:46:37.938+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=refresh_token, task_id=fresh, execution_date=20230522T162559, start_date=20230523T154637, end_date=20230523T154637
[2023-05-23T15:46:37.956+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 30 for task fresh (refresh() missing 1 required positional argument: 'self'; 274)
[2023-05-23T15:46:37.989+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-23T15:46:38.009+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
