[2023-05-23T17:56:38.012+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_token.ETL manual__2023-05-23T17:54:32.171118+00:00 [queued]>
[2023-05-23T17:56:38.025+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_token.ETL manual__2023-05-23T17:54:32.171118+00:00 [queued]>
[2023-05-23T17:56:38.025+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T17:56:38.025+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-05-23T17:56:38.025+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T17:56:38.043+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): ETL> on 2023-05-23 17:54:32.171118+00:00
[2023-05-23T17:56:38.050+0000] {standard_task_runner.py:55} INFO - Started process 3460 to run task
[2023-05-23T17:56:38.055+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'refresh_token', 'ETL', 'manual__2023-05-23T17:54:32.171118+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/refresh_token_DAG.py', '--cfg-path', '/tmp/tmpze9o1n9e']
[2023-05-23T17:56:38.059+0000] {standard_task_runner.py:83} INFO - Job 65: Subtask ETL
[2023-05-23T17:56:38.145+0000] {task_command.py:388} INFO - Running <TaskInstance: refresh_token.ETL manual__2023-05-23T17:54:32.171118+00:00 [running]> on host 2a789c3fa429
[2023-05-23T17:56:38.244+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=fox
AIRFLOW_CTX_DAG_ID=refresh_token
AIRFLOW_CTX_TASK_ID=ETL
AIRFLOW_CTX_EXECUTION_DATE=2023-05-23T17:54:32.171118+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-23T17:54:32.171118+00:00
[2023-05-23T17:56:38.608+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Spotify_ETL.py", line 60, in run_spotify_etl
    for song in resource['items']:
KeyError: 'items'
[2023-05-23T17:56:38.618+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=refresh_token, task_id=ETL, execution_date=20230523T175432, start_date=20230523T175638, end_date=20230523T175638
[2023-05-23T17:56:38.634+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 65 for task ETL ('items'; 3460)
[2023-05-23T17:56:38.669+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-23T17:56:38.696+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
