[2023-05-22T16:34:08.192+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_token.fresh scheduled__2023-05-21T00:00:00+00:00 [queued]>
[2023-05-22T16:34:08.207+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_token.fresh scheduled__2023-05-21T00:00:00+00:00 [queued]>
[2023-05-22T16:34:08.208+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-22T16:34:08.208+0000] {taskinstance.py:1283} INFO - Starting attempt 5 of 6
[2023-05-22T16:34:08.208+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-22T16:34:08.226+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): fresh> on 2023-05-21 00:00:00+00:00
[2023-05-22T16:34:08.231+0000] {standard_task_runner.py:55} INFO - Started process 1394 to run task
[2023-05-22T16:34:08.233+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'refresh_token', 'fresh', 'scheduled__2023-05-21T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/refresh_token_DAG.py', '--cfg-path', '/tmp/tmp6zd8862g']
[2023-05-22T16:34:08.235+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask fresh
[2023-05-22T16:34:08.304+0000] {task_command.py:388} INFO - Running <TaskInstance: refresh_token.fresh scheduled__2023-05-21T00:00:00+00:00 [running]> on host 3dac4c67abd7
[2023-05-22T16:34:08.390+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=fox
AIRFLOW_CTX_DAG_ID=refresh_token
AIRFLOW_CTX_TASK_ID=fresh
AIRFLOW_CTX_EXECUTION_DATE=2023-05-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-21T00:00:00+00:00
[2023-05-22T16:34:08.391+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: refresh() missing 1 required positional argument: 'self'
[2023-05-22T16:34:08.401+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=refresh_token, task_id=fresh, execution_date=20230521T000000, start_date=20230522T163408, end_date=20230522T163408
[2023-05-22T16:34:08.417+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task fresh (refresh() missing 1 required positional argument: 'self'; 1394)
[2023-05-22T16:34:08.446+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-22T16:34:08.470+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
