[2023-05-24T15:26:42.284+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: refresh_token.token scheduled__2023-05-23T00:00:00+00:00 [queued]>
[2023-05-24T15:26:42.301+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: refresh_token.token scheduled__2023-05-23T00:00:00+00:00 [queued]>
[2023-05-24T15:26:42.318+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-24T15:26:42.318+0000] {taskinstance.py:1283} INFO - Starting attempt 6 of 7
[2023-05-24T15:26:42.318+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-24T15:26:42.350+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): token> on 2023-05-23 00:00:00+00:00
[2023-05-24T15:26:42.357+0000] {standard_task_runner.py:55} INFO - Started process 569 to run task
[2023-05-24T15:26:42.363+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'refresh_token', 'token', 'scheduled__2023-05-23T00:00:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/refresh_token_DAG.py', '--cfg-path', '/tmp/tmpt2pjip43']
[2023-05-24T15:26:42.365+0000] {standard_task_runner.py:83} INFO - Job 82: Subtask token
[2023-05-24T15:26:42.535+0000] {task_command.py:388} INFO - Running <TaskInstance: refresh_token.token scheduled__2023-05-23T00:00:00+00:00 [running]> on host 2fa3ade57007
[2023-05-24T15:26:42.701+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=fox
AIRFLOW_CTX_DAG_ID=refresh_token
AIRFLOW_CTX_TASK_ID=token
AIRFLOW_CTX_EXECUTION_DATE=2023-05-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-23T00:00:00+00:00
[2023-05-24T15:26:42.922+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Spotify_ETL.py", line 60, in run_spotify_etl
    for song in resource['items']:
KeyError: 'items'
[2023-05-24T15:26:42.937+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=refresh_token, task_id=token, execution_date=20230523T000000, start_date=20230524T152642, end_date=20230524T152642
[2023-05-24T15:26:42.971+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 82 for task token ('items'; 569)
[2023-05-24T15:26:43.027+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-24T15:26:43.144+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
